### ISSUE TITLE
What about 1.0.0?

### ISSUE THREAD

**Issue by Kikobeats** [jimeh/node-base58#1]
I think that the library works fine, time to release stable version!

Maybe could be desirable write the library using vanilla javascript instead of coffeescript to avoid register a transpiler in the global context.

**Comment by jimeh** [comment]
There's now a `1.x` release, `1.0.1` to be exact. And the library is now in vanilla JS rather than coffeescript.

For what's it's worth, confusing as it may have been, even though the source code was coffeescript, the npm packages only contained the compiled vanilla JS output from coffeescript, so you didn't need coffeescript at runtime :)
